services:
  movie-db:
    build: .
    container_name: movie-db
    ports:
      - "11000:3000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - OMDB_API_KEY=${OMDB_API_KEY}
    volumes:
      - /mnt/user/appdata/movie-db:/data
      - /mnt/user/media/tv/FilmeHD:/media:ro
    restart: unless-stopped
